[project]
name = "clens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "k4rkie", email = "karkeekrish07@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi[standard]>=0.142.2",
    "filetype>=1.2.0",
    "pillow>=12.3.0",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
clens = "clens.cli:cli"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pyright]
exclude = [
    ".venv",
    "venv",
    ".chroma_store",
    "__pycache__",
]

